ARG AV_VERSION
ARG CUDA_VERSION
ARG ROCKY_VERSION
FROM alicevision/alicevision:${AV_VERSION}-rocky${ROCKY_VERSION}-cuda${CUDA_VERSION}
LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime=nvidia meshroom

# Install libs needed by Qt
RUN dnf update -y --nobest

RUN dnf install -y \
        # Python / pip (needed by aqtinstall)
        python3 \
        python3-pip \
        # Qt runtime/build dependencies
        flex fontconfig freetype glib2-devel libICE \
        libX11 libXext libXi libXrender libSM \
        libXt-devel mesa-libGLU-devel mesa-libGL-devel mesa-libEGL-devel \
        zlib-devel systemd openssh-server \
        libxcb-devel \
        libxkbcommon-devel \
        libxkbcommon-x11-devel \
        xcb-util-wm xcb-util-image \
        xcb-util-keysyms \
        xcb-util-renderutil \
        libglvnd-opengl

RUN pip3 install --upgrade pip && \
    pip3 install aqtinstall

    
ENV QT_VERSION=6.8.3
ENV QT_ARCH=linux_gcc_64
ENV QT_ARCH_SHORT=gcc_64
ENV QT_MODULES="qtcharts qt3d qtshadertools"
ENV QT_DIR=/opt/Qt
ENV QT_ROOT=/opt/Qt/${QT_VERSION}/${QT_ARCH_SHORT}

# Install Qt (to build plugins)
RUN aqt install-qt \
      --outputdir "${QT_DIR}" \
      linux desktop "${QT_VERSION}" "${QT_ARCH}" \
      -m ${QT_MODULES}

# Strip sections containing ".note.ABI.tag" from .so: https://github.com/Microsoft/WSL/issues/3023
# RUN find ${QT_DIR}/lib/ -name '*.so' | xargs strip --remove-section=.note.ABI-tag

ENV MESHROOM_DEV=/opt/Meshroom

COPY ./*requirements.txt ${MESHROOM_DEV}/

# Install Meshroom requirements and freeze bundle
WORKDIR "${MESHROOM_DEV}"
RUN python -m pip install -r dev_requirements.txt -r requirements.txt
