ARG AV_IMAGE
FROM ${AV_IMAGE}
LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime=nvidia meshroom

ARG QT_VERSION=6.8.3

ENV MESHROOM_DEV=/opt/Meshroom \
    MESHROOM_BUILD=/tmp/Meshroom_build \
    QT_VERSION=${QT_VERSION} \
    QT_DIR=/opt/Qt/${QT_VERSION}/gcc_64

# Install libs needed by Qt
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        flex \
        fontconfig \
        libfreetype6 \
        libglib2.0-0 \ 
        libice6 \
        libx11-6 \
        libxcb1 \
        libxext6 \
        libxi6 \
        libxrender1 \
        libsm6

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        libxt-dev \
        libosmesa-dev \
        libgl-dev \
        libegl-dev \
        libglu-dev \
        libxkbcommon-x11-0 \
        libz-dev \
        systemd \
        ssh

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        libxcb1-dev \
        libxcb-icccm4 \
        libxcb-render-util0 \
        libxcb-shape0 \
        libxcb-keysyms1 \
        libxcb-image0 \
        libxkbcommon-dev

RUN apt-get install -y --no-install-recommends \
	software-properties-common

# Install Python3
# RUN apt install python3.11-pip -y && pip3 install --upgrade pip

# Enable SSH X11 forwarding, needed when the Docker image is run on a remote machine
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ssh xauth && \
    systemctl enable ssh && \
    mkdir -p /run/sshd && \
    sed -i "s/^.*X11Forwarding.*$/X11Forwarding yes/; s/^.*X11UseLocalhost.*$/X11UseLocalhost no/; s/^.*PermitRootLogin prohibit-password/PermitRootLogin yes/; s/^.*X11UseLocalhost.*/X11UseLocalhost no/;" /etc/ssh/sshd_config && \
    echo "root:meshroom" | chpasswd

# Install Qt (to build plugins) with aqtinstall. It is installed in a throwaway
# directory so that it does not end up in the Python environment of the image.
RUN python3.11 -m pip install --no-cache-dir --target /tmp/aqt aqtinstall==3.3.0 && \
    PYTHONPATH=/tmp/aqt python3.11 -m aqt install-qt linux desktop ${QT_VERSION} linux_gcc_64 \
        -m qtcharts qt3d --outputdir /opt/Qt && \
    rm -rf /tmp/aqt

# Strip sections containing ".note.ABI.tag" from .so: https://github.com/Microsoft/WSL/issues/3023
RUN find ${QT_DIR}/lib/ -name '*.so' | xargs strip --remove-section=.note.ABI-tag

COPY ./*requirements.txt ./setup.py ${MESHROOM_DEV}/

# Install Meshroom requirements and freeze bundle
WORKDIR "${MESHROOM_DEV}"
RUN python3.11 -m pip install -r dev_requirements.txt -r requirements.txt
