# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

# Meshroom dependencies, on top of the AliceVision image (AV_IMAGE).
# Built by docker/build-image.sh.

ARG AV_IMAGE
FROM ${AV_IMAGE}
LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

ARG QT_VERSION=6.8.3
ENV QT_VERSION=${QT_VERSION} \
    QT_DIR=/opt/Qt/${QT_VERSION}/gcc_64

# Fail a RUN on any error in a pipe, not only the last command
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# System packages: libraries needed by Qt and SSH with X11 forwarding (needed when the
# Docker image is run on a remote machine). The cache mount avoids re-downloading
# the packages on rebuild.
RUN --mount=type=cache,target=/var/cache/dnf \
    dnf install -y --setopt=keepcache=True \
        flex \
        fontconfig \
        freetype \
        glib2-devel \
        libglvnd-opengl \
        libICE \
        libSM \
        libX11 \
        libxcb-devel \
        libXext \
        libXi \
        libxkbcommon-devel \
        libxkbcommon-x11-devel \
        libXrender \
        libXt-devel \
        mesa-libEGL-devel \
        mesa-libGL-devel \
        mesa-libGLU-devel \
        openssh \
        openssh-clients \
        openssh-server \
        systemd \
        xcb-util-image \
        xcb-util-keysyms \
        xcb-util-renderutil \
        xcb-util-wm \
        xorg-x11-xauth \
        zlib-devel && \
    systemctl enable sshd && \
    mkdir -p /run/sshd && \
    ssh-keygen -A && \
    sed -i "s/^.*X11Forwarding.*$/X11Forwarding yes/; s/^.*X11UseLocalhost.*$/X11UseLocalhost no/; s/^.*PermitRootLogin prohibit-password/PermitRootLogin yes/; s/^.*X11UseLocalhost.*/X11UseLocalhost no/;" /etc/ssh/sshd_config && \
    echo "root:meshroom" | chpasswd

# System libraries the Meshroom image copies into its bundle.
# libOpenGL: needed by QtAliceVision as a side effect of a Qt6 bug
ENV BUNDLE_EXTRA_LIBS="/usr/lib64/libOpenGL.so.0"

# Install Qt (to build plugins) with aqtinstall. It is installed in a throwaway
# directory so that it does not end up in the Python environment of the image.
# Strip sections containing ".note.ABI.tag" from .so (https://github.com/Microsoft/WSL/issues/3023)
# in the same RUN, otherwise every stripped library is stored twice in the image.
RUN python3.11 -m pip install --no-cache-dir --target /tmp/aqt aqtinstall==3.3.0 && \
    PYTHONPATH=/tmp/aqt python3.11 -m aqt install-qt linux desktop ${QT_VERSION} linux_gcc_64 \
        -m qtcharts qt3d qtshadertools --outputdir /opt/Qt && \
    rm -rf /tmp/aqt && \
    find ${QT_DIR}/lib/ -name '*.so' | xargs strip --remove-section=.note.ABI-tag

# Install Meshroom requirements
RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    --mount=type=bind,source=dev_requirements.txt,target=/tmp/dev_requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
    python3.11 -m pip install -r /tmp/dev_requirements.txt -r /tmp/requirements.txt
