ARG AV_VERSION
ARG CUDA_VERSION
ARG ROCKY_VERSION
FROM alicevision/alicevision:${AV_VERSION}-rocky${ROCKY_VERSION}-cuda${CUDA_VERSION}
LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

# Execute with nvidia docker (https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0))
# docker run -it --runtime=nvidia meshroom

ARG QT_VERSION=6.8.3

ENV MESHROOM_DEV=/opt/Meshroom \
    MESHROOM_BUILD=/tmp/Meshroom_build \
    QT_VERSION=${QT_VERSION} \
    QT_DIR=/opt/Qt/${QT_VERSION}/gcc_64

# Install libs needed by Qt
RUN dnf install -y flex fontconfig freetype glib2-devel libICE
RUN dnf install -y libX11 libXext libXi libXrender libSM
RUN dnf install -y libXt-devel mesa-libGLU-devel mesa-libGL-devel mesa-libEGL-devel
RUN dnf install -y zlib-devel systemd openssh-server
RUN dnf install -y libxcb-devel \
                   libxkbcommon-devel \
                   libxkbcommon-x11-devel \
                   xcb-util-wm xcb-util-image \
                   xcb-util-keysyms \
                   xcb-util-renderutil
RUN dnf install -y libglvnd-opengl

# Install Qt (to build plugins) with aqtinstall. It is installed in a throwaway
# directory so that it does not end up in the Python environment of the image.
RUN python3.11 -m pip install --no-cache-dir --target /tmp/aqt aqtinstall==3.3.0 && \
    PYTHONPATH=/tmp/aqt python3.11 -m aqt install-qt linux desktop ${QT_VERSION} linux_gcc_64 \
        -m qtcharts qt3d --outputdir /opt/Qt && \
    rm -rf /tmp/aqt

# Strip sections containing ".note.ABI.tag" from .so: https://github.com/Microsoft/WSL/issues/3023
RUN find ${QT_DIR}/lib/ -name '*.so' | xargs strip --remove-section=.note.ABI-tag

COPY ./*requirements.txt ${MESHROOM_DEV}/

# Install Meshroom requirements and freeze bundle
WORKDIR "${MESHROOM_DEV}"
RUN python3.11 -m pip install -r dev_requirements.txt -r requirements.txt
 