
from meshroom.core import desc

class ImageMatching(desc.CommandLineNode):
    internalFolder = '{cache}/{nodeType}/{uid0}/'
    commandLine = 'openMVG_main_generatePairList {allParams}'

    verbose = desc.ParamAttribute(
            label='Verbose',
            description='''Verbosity level, 0 to mute.''',
            value=1,
            shortName='v',
            arg='arg',
            uid=[0],
            )
    weights = desc.FileAttribute(
            label='Weights',
            description='''Input name for the weight file, if not provided the weights will be computed on the database built with the provided set.''',
            value='',
            shortName='w',
            arg='arg',
            uid=[0],
            )
    tree = desc.FileAttribute(
            label='Tree',
            description='''Input name for the tree file''',
            value='',
            shortName='t',
            arg='arg',
            uid=[0],
            )
    keylist = desc.FileAttribute(
            label='Keylist',
            description='''Path to the list file (list.txt or sfm_data) generated by OpenMVG or the path to a directory containing the descriptors.''',
            value='',
            shortName='l',
            arg='arg',
            uid=[0],
            )
    nbMaxDescriptors = desc.ParamAttribute(
            label='Nb Max Descriptors',
            description='''Limit the number of descriptors you load per image. Zero means no limit.''',
            value=0,
            shortName='m',
            arg='arg',
            uid=[0],
            )
    outfile = desc.FileAttribute(
            label='Outfile',
            description='''(=pairList.txt) Name of the output file.''',
            value='',
            shortName='o',
            arg='arg',
            uid=[0],
            )