# .github/workflows/continuous-integration.yml

name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'

jobs:
  test-linux:
    name: Test (Linux)
    uses: ./.github/workflows/run-tests.yml
    with:
      os: ubuntu-latest
      python-version: '3.11'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-windows:
    name: Test (Windows)
    uses: ./.github/workflows/run-tests.yml
    with:
      os: windows-latest
      python-version: '3.11'
